### ISSUE TITLE
Action always fails

### ISSUE THREAD

**Issue by SimonSchick** [deepsourcelabs/test-coverage-action#22]
```exit status 128
Traceback (most recent call last):
  File "/app/main.py", line 62, in <module>
    main()
  File "/app/main.py", line 58, in main
​
    print(process.err.decode("utf-8"), file=sys.stderr)
AttributeError: 'CompletedProcess' object has no attribute 'err'
```

https://github.com/deepsourcelabs/test-coverage-action/commit/8b4972516b1d36fb43650562f28161d63bdb6770#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R58 is the culprit.

I strongly suggest you use mypy/pyright in the future to avoid such relatively easily preventable breakages, also consider adding tests.

**Comment by SimonSchick** [comment]
Also I strongly advice you to release versions of your gh action and to perform pre-release testing, telling people to depend on `@master` is not a good idea for production lvl code.

**Comment by tushar-deepsource** [comment]
@SimonSchick Sorry for the breakage; the action wasn't working even before the code change happened, read [this post](https://discuss.deepsource.io/t/breaking-deepsource-test-coverage-github-action/507) for more context.

The action, both the latest release and the `master` branch should be working now.

I'll remove the `@master` recommendation from the README and the documentation. We do make releases to marketplace already.
